name: Mega Games
version: 1.0
author: Mega
main: fr.mega.megagames.Main
commands:
  duel:
    description: Vous permez de défiez un joueur
  accept:
    description: La mère à mega
  refuser:
    description: Le papa à mega